version: '3.1'

services:
  devdojomicroservice:
    image: mysql:5.7
    volumes:
      - ./devdojomicroservices:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devdojomicroservices
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_allowed_packet=256M --sql-mode=''
